Add the ability to delete list entries with Backspace.
derikb/character-sheet-app pull request #108
Opened 2022-02-25 01:16 UTC by kyledhardison

I get a lot of use out of your tool in my D&D games, and really appreciate the work you've put into it.

While using it, I noticed that there wasn't any way to delete empty list entries that I mistakenly made, so I added the ability to delete blank list items by pressing backspace.

This applies to `SimpleList`, `NoteList`, and `TableEditable` types. 

I also pulled the `KeyPress` logic from `NoteListEntry` up to `NoteList` for simplicity.

2022-02-25 01:18 UTC, kyledhardison commented on src/components/NoteList.js
> +                if (el.parentNode.host !== this.shadowRoot.children[1]) {
I did similar things to this in several places because the 0th object in `this.shadowRoot.children` is a `style` element, so the first list entry will always be `this.shadowRoot.children[1]`.

I'm not a huge JS guy, is there a more elegant way to do this?

2022-02-26 14:54 UTC, derikb requested changes
Thanks for the idea (a good one) and the PR, Kyle.

1) I added an issue for the idea.
2) I switched the base branch to one named for that issue, though it could also just be set to develop branch. In the majority of repos I would think you never set master/main as your base branch unless you are merging code that is ready for release.
3) not sure what you code in, but some of these comments (the repetitive ones) are just syntax/style things from the eslint config. Most IDEs can pick that up and mark up your files to find them.

2022-02-26 14:54 UTC, derikb commented on src/components/TableEditable.js
> +        } else if (ev.key == 'Backspace') {
Since nothing happens after the this if/else block, you can just return before checking for the backspace key. Makes it clearer that there's nothing else happening for the "Enter" case.

2022-02-26 14:54 UTC, derikb commented on src/components/TableEditable.js
> +            if (td.innerHTML != '') {
Probably better to check `td.innerText`. With contenteditable elements you could end up with html in them so that might not be visible. So you could have a cell with `<span></span>` or something in it, which is not empty as far as innerHTML is concerned but would look empty to the user. innerText will more specifically target readable text content which I think is what we'd want here.

2022-02-26 14:54 UTC, derikb commented on src/components/TableEditable.js
> +            if (td.innerHTML != '') {
Also this should be `!==` strict equality is always better to use in JS. This is covered by the eslint config for the project.

2022-02-26 14:54 UTC, derikb commented on src/components/TableEditable.js
> +        if (ev.key == 'Enter') {
strict equality

2022-02-26 14:54 UTC, derikb commented on src/components/TableEditable.js
> +                const children = row.children;
Might be simpler/better to just check all the `td` children (with querySelectorAll) and also check innerText (per above).

2022-02-26 14:54 UTC, derikb commented on src/components/TableEditable.js
> +                    row.remove();
One of the "supports IE" things I have yet to get over is being able to call `remove` instead of some complicated parentNode.removeChild type syntax.

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +                el.nextElementSibling.focus();
This could not do what you think, if the DT element has pasted in HTML in it... the case where the el is not the DT but some child element (like a "strong" or something). `nextElementSibling` might then get you... something else. Or maybe nothing (null) which would then throw an error for the focus method.

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +        } else if (ev.key == 'Backspace') {
Again... strict equality and you can probably return right above it.

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +            if (el.innerHTML != '') {
Again (or first... I'm reviewing this out of order, I always forget if the comments will appear in that order), probably better as innerText and strict equality.

Occurs to me... pasted content could also leave you with invisible characters that might be leftover... between tags... like `\t` or `\n`... not sure if that could be an issue. You may also end up with spaces. Would be worth testing out... might need to applying some kind of trimming to that to confirm.

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +                if (el.parentNode.host !== this.shadowRoot.children[1]) {
See below, but I think you could use `querySelector('note-list-item')` to find the first one.

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +                        this.deepActiveElement().nextElementSibling.focus();
Confused by these two focus calls in a row... focus gets a little tricky with components and shadow DOM, but I think you'd only need the first one?

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +                        }
Again, a little trickier to confirm empty that it seems in some cases.

Since el.parentNode.host here is the `note-list-item` (I think)... I wonder if it would be simpler to add method to NoteListItem to check if it's empty. That could more simply account for text/html/spaces/etc. and be better contained.

2022-02-26 14:54 UTC, derikb commented on src/components/NoteList.js
> +                el.previousElementSibling.focus();
Again, I think this could be problematic if el is not the DD but a child of it.

2022-03-31 00:14 UTC, kyledhardison commented
Sorry about the delayed response - work and school have gotten busy.

I've addressed many of your comments, would you like me to resolve them myself?

2022-03-31 00:16 UTC, kyledhardison commented on src/components/NoteList.js
> +        this.addEventListener('keydown', this._keyDown);
That's correct, is there a better option?

2022-03-31 00:19 UTC, kyledhardison commented on src/components/NoteList.js
> +                el.nextElementSibling.focus();
If `el` is a child of `DT` then this if statement will be bypassed though, right?

2022-03-31 00:21 UTC, kyledhardison commented on src/components/NoteList.js
> +                        this.deepActiveElement().nextElementSibling.focus();
This was the only way I could manage to select the previous `note-list-item`, then select the `dd` child of it. Do you have any recommendations to do that more elegantly?

2022-03-31 01:20 UTC, kyledhardison commented on src/components/TableEditable.js
> +                    row.remove();
This is good as-is right? I'm unfamiliar with the wonderful world of supporting IE.

2022-03-31 01:37 UTC, kyledhardison commented on src/components/NoteList.js
> +                        }
It's not showing as updated but I addressed this as well.

2022-04-10 15:07 UTC, derikb requested changes

2022-04-10 15:07 UTC, derikb commented on src/components/NoteList.js
> +                        this.deepActiveElement().nextElementSibling.focus();
Did you try... `prevItem.shadowRoot.querySelector('dd').focus()` maybe? Since the shadowRoot on the NoteListItem is "open" you should be able to "pierce" the shadowDOM and access elements directly.

2022-04-10 15:07 UTC, derikb commented on src/components/NoteListItem.js
> +        return empty;
You don't really need a var here. You can just have `empty = true` be `return true;` and then `return empty;` can just be `return false`.

2022-05-10 23:05 UTC, kyledhardison commented on src/components/NoteList.js
> +                el.nextElementSibling.focus();
I took a crack at this and was unable to produce any behavior where `el` is a child of `DT`, such as inserting a `<strong>` tag. Can you tell me how to reproduce that behavior?

If not, would be better just to remove the `el.closest('dt')` part of the conditional?

2022-06-12 13:34 UTC, derikb commented
Sorry for the long delay on this @kyledhardison Going to merge this to local issue-109 branch then will test out when everything is working right get into a release.

2022-06-12 13:34 UTC, merged

2022-06-12 13:53 UTC, derikb commented
One thing I found that I am trying to solve now... is if you hit backspace you can get moved to the previous editable area, but the cursor goes to the _start_ of that area, which seems unintuitive to me. Especially if you are trying to erase that content too. So... trying to figure out how to focus but move the cursor to the end of the content...

2022-06-12 14:37 UTC, derikb commented
Another thing to watch out for. If you don't `ev.preventDefault()` on the backspace event, the cursor moves to the field and then can erase characters. This only really came to light when I switched the cursor to move to the end of the content. But always good to remember when messing with some of these events that you have to sometimes prevent the normal workings of the event.